apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: django
  template:
    metadata:
      labels: 
        pod: django
    spec:
      containers:
        - name: django
          image: knh4735/django-sample
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_DEBUG
              value: "True"

            - name: DJANGO_DB_HOST
              value: db

            - name: DJANGO_DB_PORT
              value: "5432"

            - name: DJANGO_DB_NAME
              value: sampledb

            - name: DJANGO_DB_USERNAME
              value: sampleuser

            - name: DJANGO_DB_PASSWORD
              value: samplesecret

            - name: DJANGO_SECRET_KEY
              value: dev_secret_key