apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: postgres
  template:
    metadata:
      labels: 
        pod: postgres
    spec:
      containers:
        - name: db
          image: postgres:9.6.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: sampledb

            - name: POSTGRES_USER
              value: sampleuser

            - name: POSTGRES_PASSWORD
              value: samplesecret

            - name: POSTGRES_INITDB_ARGS
              value: --encoding=UTF-8